### ISSUE TITLE
memstream broken

### ISSUE THREAD

**Issue by notspiff** [Lectem/libmpo#2]
hi,

i realize this code is most likely abandoned, but figured i'd open an issue just in case.
i have attempted to write some downstream user code, specifically an add-on for the kodi media center,
https://github.com/notspiff/imagedecoder.mpo

stdio input works fine, but memstream input immediately segfaults. is this known, or maybe i'm doing something wrong or have misunderstood something ? ref https://github.com/notspiff/imagedecoder.mpo/blob/master/src/MPOPicture.cpp#L49 vs https://github.com/notspiff/imagedecoder.mpo/blob/master/src/MPOPicture.cpp#L50

cheers,

arnem

**Comment by Lectem** [comment]
Luckily for you it was an easy fix !
Somehow I must have failed while refactoring at some point... which was fatal in this case.

Please note that while I spent quite some time working on this library because of the obscure documentation of the MPF format, this library probably isn't production ready. By that I mean that it not only lacks features but probably (certainly) is missing quite a lot of safety checks.

**Comment by notspiff** [comment]
thanks! and thanks for the warning, no worries, i won't be nagging you, i promise. i've been programming for about 20 years so i can smell the research nature of the code :) honestly this was meant as a FYI and not a support request. i see that my formulation probably wasn't all clear.

it's not quite working yet. in particular, it calls my_ftell(), which uses buffer_file_offset (which i cannot find any assignments for in the memsrc path), and this leads to rather wonky offsets.

```
skip 22 bytes (to the beggining of image 1)
Image 1 SOI offset : 1287104272(0x4cb7a710)
Not a JPEG file: starts with 0xe1 0x31
```

i tried setting the positions myself, but it won't find a jpeg header for the second image (set to the offset from the APP02 headers). i'll keep digging...

**Comment by Lectem** [comment]
I don't mind the nagging really, the whole point of the repository is to help people that want to read/write or research MPOs. 

Give 63ada10 a try, I think it might fix the issue.

**Comment by notspiff** [comment]
\o/ that did it. thanks a bunch, i love open source :)

**Comment by Lectem** [comment]
Glad it works!
Don't hesitate to open another issue if you have any question or problem
